### ISSUE TITLE
Device_map?

### ISSUE THREAD

**Issue by ThongSong7** [hayatae/gale-home-assistant-skill#1]
Hello!  I am trying to see if your solution would integrate into my HASS instance - I cannot get the official from Mycroft working, however I cannot seem to figure out what "device_map" means or even is.... could you kindly help me?

I have tried things like:
"office": "light.bulb33" and many different variations thereof but always tells me "WrOnG!"

Thanks for your attention and eventual assistance :)

**Comment by hayatae** [comment]
Hah, I actually never expected anyone else to find or use this skill. It's pretty custom tailored to my own needs right now, but I think I can help you out!

After you have the skill installed, go to the "Configure your skills" page on the mycroft.ai website, and scroll down to the settings for "Gale Home Assistant". There you'll see settings for "Login" and "Devices". Make sure your login host address and long lived access token is set there. For the "Device Map" setting, this is a JSON string with the following format:

```
{
  "switch": {
    "spoken name": "homeassistant_device_id",
  },
  "light": {
    "spoken name": "homeassistant_device_id",
  },
  "scene": { "spoken name": "scene.scene_id" },
  "script": { "spoken name": "script.script_id" }
}
```

As an example, here's what part of mine looks like:
```
{
  "switch": {
    "basement": "group.basement",
    "tv": "input_boolean.tv"
  },
  "light": {
    "bedroom": "light.bedroom_lights",
    "kitchen": "light.kitchen_lights"
  },
  "scene": { "bedtime": "scene.bedtime" },
  "script": { "good morning": "script.12348281234" }
}
```

The difference between an entry in "switch" and an entry in "light" is that lights can be dimmed. For example, you can say "Set bedroom to 10%" to dim the lights to 10%. Entries in the switch categories are only on/off switches (non-dimming lights, fans, etc).

**Comment by ThongSong7** [comment]
Super!  
Thank you for your help... 
I am putting this in the config via home.-mycroft-.ai/skills but the spacing is all off since it is only one line, in the cli it is returning as WrOnG!  

I configured the local settings.json as normally structured and mycroft tells me "'location' is unknown" which I suppose is better than before.

So if I change the 'local' file to what you instructed, it does not work.  I cannot seem to get any correct formatting via the home.ai interface and therefore nothing reflecting back locally. Is there anything I can do at this stage to get my devices mapped correctly and for Mycroft to pick it up?

Maybe modify all of this in some another local file?   I would really love to get this working for the WoW factor alone!

Thanks again for your assistance! :)

**Comment by ThongSong7** [comment]
I have added the other brackets as in your post.... it is not saying that it is wrong now!  Great step! 
Now I am getting "the kitchen device is not known" - probably now a formatting problem in my json.... I will check it again, but it I am getting there.  "the office device is unknown".

 >> I don't know what that means.                                                                                                                                                                                    
 turn on the office light                                                                                                                                                                                       
 >> I'm not sure what the office is                                                                                                                                                                                      
 turn on the office light                                                                                                                                                                                                           
 >> the office device is unknown                                                                                                                                                                                                    
 turn on the light in the office                                                                                                                                                                                            
 >> I couldn't find the light in the office  
 
my json code was validated via jsonlint-dot-com also if this helps....

**Comment by hayatae** [comment]
Ah, I see your problem - my code actually doesn't handle the word "the" right now. You would instead need to say:
"Turn on office light" or "Turn on office" (the word "light" is optional) if the key in your device map is "office"

**Comment by hayatae** [comment]
I've just pushed an update to allow for optional use of the word "the" in the command. Let me know if it works after the update!

**Comment by ThongSong7** [comment]
![image](https://user-images.githubusercontent.com/23183570/112101627-434f4580-8ba7-11eb-8fa8-dd2c9dc9f01f.png)
OMG!  Fantastic!
Thank you so very much!  
This is awesome!
From the above you can assume that it is working great. :)
Thank you for your help and commitment, you rock!
